---
sudo: false
language: ruby
cache: bundler
rvm:
  - jruby-9.2.0.0
before_install: gem install bundler -v 1.16.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - jruby -G bin/rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
